---
- hosts: 172.31.30.93
  become:
  tasks:
    - name: i want to execute direct linux command
      command: hostname -f
      register: mycommandresult

    - name: i want to print that command result 
      debug: 
        msg: "{{mycommandresult}}"

    - name: install git
      apt:
        name: git
        state: present
      when: mycommandresult.stderr !="" 

    - name: install wget
      apt: 
        name: wget
        state: present
      when: mycommandresult.stderr =="" 