---
- hosts: 172.31.30.93
  become: yes
  tasks:
    - include_tasks: myfile.yml

    - name: install webserver on ubuntu server
      apt:
        name: apache2 
        state: present 
      

    - name: copy static file from laptop to ubuntu Node side 
      copy:
        src: mystaticfile
        dest: /home/ubuntu/  

    - name: download tomcat tar internet file
      get_url: 
         url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
         dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz

    - name: change index page information
      template:
         src: myindex.j2
         dest: /var/www/html/index.html
      notify: installgit

  handlers:
    - name: installgit
      apt:
        name: git
        state: present

         