---
- hosts: 172.31.30.93
  become: yes
  tasks:
    - include_tasks: myfile.yml

    - name: install webserver on RedHat server
      dnf:
        name: httpd
        state: present 
      when: ansible_os_family =="RedHat"

    - name: copy static file from laptop to ubuntu Node side 
      copy:
        src: mystaticfile
        dest: /home/ubuntu/  