---
- hosts: 172.31.31.126
  become: yes
  tasks:
    - include_tasks: myfile.yml

    - name: install webserver on RedHat server
      dnf:
        name: httpd
        state: present 
      when: ansible_os_family =="RedHat"