---
- hosts: 172.31.30.93
  become: yes
  vars:
    - var01: git 
    - var02: wget
    - var03: apache2
    - var04: rupesh deore

  tasks:
     - name: print var04 
       debug:
         msg: "{{var04}}"