---
- hosts: mywebserver
  become: yes
  tasks:
    - name: installing webserver on hosts
      apt:
        name: "{{mywebpackageonUbuntu}}"
        state: present
      when: ansible_os_family =="Debian"

    - name: starting webserver service
      service:
         name: "{{mywebpackageonUbuntu}}"
         state: started
      when: ansible_os_family =="Debian"

    - name: i want to install webserver on RedHat 
      dnf:
        name: "{{mywebpackageonRedHat}}"
        state: present
      when: ansible_os_family =="RedHat"

    - name: lets start the webserver on RedHat 
      service:
         name: "{{mywebpackageonRedHat}}"
         state: started
      when: ansible_os_family =="RedHat"

    - name: installing java-11 package on Ubuntu Node
      apt:
        name: "{{javapackonUbuntu}}"
        state: present
      when: ansible_os_family =="Debian"

    - name: installing java-11 package on RedHat Node
      dnf:
        name: "{{javapackonRedHat}}"
        state: present
      when: ansible_os_family =="RedHat"