---
- hosts: 172.31.31.126
  become: yes
  tasks:
    - name: installing webserver on hosts
      apt:
        name: apache2
        state: present
      when: ansible_os_family =="Debian"

    - name: starting webserver service
      service:
         name: apache2
         state: started
      when: ansible_os_family =="Debian"